### ISSUE TITLE
PRs for models

### ISSUE THREAD

**Issue by tirthasheshpatel** [Shrey-Viradiya/Pneumonia_Detection#28]
We need to keep track of all the models we have trained so far. So, let's push them onto different branches and create a pull request. We will later merge them all together. Here are the models and their pull request:

- [x] GoogleNet (@Shrey-Viradiya) #30
- [x] Inception (@Shrey-Viradiya) #29 
- [x] ResNet50 (@Shrey-Viradiya) #37
- [x] ResNet101 (@tirthasheshpatel) #36
- [x] ResNet152 (@Shrey-Viradiya) #31 
- [x] VGG19 (@Shrey-Viradiya) #32

@tirth-hihoriya @Tirth1306 @Shrey-Viradiya
